### ISSUE TITLE
alpine 3.9 support

### ISSUE THREAD

**Issue by oadam** [madnight/docker-alpine-wkhtmltopdf#3]
I've been using your build steps with great success for the past few month but I'm having issues adapting it to alpine 3.9 .

The apk install is failing because the `libssl1.0` package has been removed :
* https://pkgs.alpinelinux.org/package/v3.8/main/x86/libssl1.0 is working
* https://pkgs.alpinelinux.org/package/v3.9/main/x86/libssl1.0 is not

I tried using `libssl1.1` instead but the `wkhtmltopdf` binary was complaining about missing symbols.

**Comment by madnight** [comment]
Maybe you can try:

```sh 
echo 'http://dl-cdn.alpinelinux.org/alpine/v3.8/main' >> /etc/apk/repositories
apk add libssl1.0
```

**Comment by mareksuscak** [comment]
Or change to `libssl1.1` and `libcrypto1.1` since these ones're available - https://pkgs.alpinelinux.org/packages?name=libssl*&branch=v3.9

EDIT1: actually that wouldn't work since the binary was clearly compiled with `libssl1.0`

EDIT2: check this out https://github.com/Surnet/docker-wkhtmltopdf (includes the build script), i'm gonna contribute a patch for alpine 3.9

EDIT3: There is a PR now - https://github.com/Surnet/docker-wkhtmltopdf/pull/7

**Comment by madnight** [comment]
@mareksuscak ah well done, nice work

Hm maybe my repository doesn't make sense anymore, since the Surnet approach seems to be way better than my pre-compiled binary copy approach.

**Comment by mareksuscak** [comment]
Well, the end goal is to support Alpine Linux in [the official repository](https://github.com/wkhtmltopdf/packaging) from what I can tell. See https://github.com/wkhtmltopdf/packaging/issues/2

**Comment by madnight** [comment]
The binary supports alpine 3.10 now (is linked against libssl1.1 and libcrypto1.1). However, I strongly recommend https://github.com/Surnet/docker-wkhtmltopdf
